image: tmaier/docker-compose:latest

services:
  - docker:dind

before_script:
  - docker info
  - docker-compose --version

build:
  stage: build
  script:
    - echo "$ENV_PRODUCTION" > .env
    - docker stop spaikeda || true && docker rm spaikeda || true
    - docker login -u antoniocometa --password 2f9d350d-8c1e-4490-b895-f6cca4163a01
    - docker-compose build

deploy:
  stage: deploy
  script:
    - echo "$ENV_PRODUCTION" > .env
    - docker-compose up -d
