version: "3.7"

services:
  spaikeda:
    container_name: spaikeda
    image: spaikeda
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - 8083:8083
